// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportMap.Infrastructure.Data;

#nullable disable

namespace SportMap.Infrastructure.Migrations
{
    [DbContext(typeof(SportMapDbContext))]
    [Migration("20260429190057_AddLocations")]
    partial class AddLocations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportMap.Core.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("SportMap.Core.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("HasLights")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ProposedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Sports")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Surface")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProposedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("Locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Str. General Magheru 1, Oradea",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLights = true,
                            Latitude = 47.051100m,
                            Longitude = 21.923900m,
                            Name = "Stadionul Municipal Iuliu Bodola",
                            Sports = "football",
                            Status = 1,
                            Surface = "grass"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Str. Politehnicii 1, Oradea",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLights = true,
                            Latitude = 47.062800m,
                            Longitude = 21.911300m,
                            Name = "Baza Olimpică de Natație Oradea",
                            Sports = "swimming",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "Calea Bihorului 100, Oradea",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLights = false,
                            Latitude = 47.055100m,
                            Longitude = 21.933100m,
                            Name = "Pista de Ciclism Parcul Brătianu",
                            Sports = "cycling",
                            Status = 1,
                            Surface = "asphalt"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Calea Sântandrei 77, Oradea",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLights = true,
                            Latitude = 47.071200m,
                            Longitude = 21.928700m,
                            Name = "Complexul de Tenis Lotus",
                            Sports = "tennis",
                            Status = 1,
                            Surface = "clay"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Calea Borșului 35, Oradea",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLights = true,
                            Latitude = 47.062100m,
                            Longitude = 21.907300m,
                            Name = "XT Gold Arena",
                            Sports = "basketball,handball",
                            Status = 1,
                            Surface = "hardcourt"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Str. Universității 1, Oradea",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLights = true,
                            Latitude = 47.046900m,
                            Longitude = 21.933200m,
                            Name = "Sala de Sport a Universității",
                            Sports = "volleyball,basketball,badminton",
                            Status = 1,
                            Surface = "hardcourt"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Str. General Magheru 1, Oradea",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLights = false,
                            Latitude = 47.051200m,
                            Longitude = 21.924100m,
                            Name = "Pista de Atletism Iuliu Bodola",
                            Sports = "athletics",
                            Status = 1,
                            Surface = "tartan"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Str. Menumorut 3, Oradea",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLights = true,
                            Latitude = 47.052100m,
                            Longitude = 21.920100m,
                            Name = "Sala Sporturilor Oradea",
                            Sports = "handball",
                            Status = 1,
                            Surface = "hardcourt"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Piața Unirii 4, Oradea",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLights = true,
                            Latitude = 47.047800m,
                            Longitude = 21.919400m,
                            Name = "Centrul Fitness SportMap Park",
                            Sports = "fitness",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            Address = "Str. Republicii 22, Oradea",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLights = true,
                            Latitude = 47.046500m,
                            Longitude = 21.918900m,
                            Name = "Sala de Box Crișul",
                            Sports = "boxing",
                            Status = 1
                        });
                });

            modelBuilder.Entity("SportMap.Core.Entities.Participation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ActivityId", "UserId")
                        .IsUnique();

                    b.ToTable("Participations", (string)null);
                });

            modelBuilder.Entity("SportMap.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmailConfirmationToken")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("EmailConfirmationTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("FavoriteSports")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsEmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SportMap.Core.Entities.Activity", b =>
                {
                    b.HasOne("SportMap.Core.Entities.Location", "Location")
                        .WithMany("Activities")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportMap.Core.Entities.User", "Organizer")
                        .WithMany("OrganizedActivities")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("SportMap.Core.Entities.Location", b =>
                {
                    b.HasOne("SportMap.Core.Entities.User", "ProposedBy")
                        .WithMany()
                        .HasForeignKey("ProposedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProposedBy");
                });

            modelBuilder.Entity("SportMap.Core.Entities.Participation", b =>
                {
                    b.HasOne("SportMap.Core.Entities.Activity", "Activity")
                        .WithMany("Participations")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportMap.Core.Entities.User", "User")
                        .WithMany("Participations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportMap.Core.Entities.Activity", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("SportMap.Core.Entities.Location", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("SportMap.Core.Entities.User", b =>
                {
                    b.Navigation("OrganizedActivities");

                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
