// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportMap.Infrastructure.Data;

#nullable disable

namespace SportMap.Infrastructure.Migrations
{
    [DbContext(typeof(SportMapDbContext))]
    [Migration("20260430103749_AddFriendships")]
    partial class AddFriendships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportMap.Core.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("SportMap.Core.Entities.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("FolloweeId")
                        .HasColumnType("int");

                    b.Property<int>("FollowerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FolloweeId");

                    b.HasIndex("FollowerId", "FolloweeId")
                        .IsUnique();

                    b.ToTable("Friendships", (string)null);
                });

            modelBuilder.Entity("SportMap.Core.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("HasLights")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("MainPhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ProposedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("SecondaryPhotoUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sports")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Surface")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProposedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("Locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Str. General Magheru 1, Oradea",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Details = "Stadionul Municipal Iuliu Bodola este principala arenă de fotbal din Oradea, cu o capacitate de 19.000 de locuri. Dispune de teren de gazon natural, vestiare moderne și tribune acoperite.",
                            HasLights = true,
                            Latitude = 47.051100m,
                            Longitude = 21.923900m,
                            MainPhotoUrl = "https://picsum.photos/seed/stadion-oradea/800/500",
                            Name = "Stadionul Municipal Iuliu Bodola",
                            SecondaryPhotoUrls = "[\"https://picsum.photos/seed/stadion-oradea-2/800/500\",\"https://picsum.photos/seed/stadion-oradea-3/800/500\"]",
                            Sports = "football",
                            Status = 1,
                            Surface = "grass"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Str. Politehnicii 1, Oradea",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Details = "Bazin olimpic acoperit cu 8 culoare, lungime 50m. Ideal pentru antrenamente de înot competițional și recreațional. Dispune de bazin de sărituri și saune.",
                            HasLights = true,
                            Latitude = 47.062800m,
                            Longitude = 21.911300m,
                            MainPhotoUrl = "https://picsum.photos/seed/piscina-oradea/800/500",
                            Name = "Baza Olimpică de Natație Oradea",
                            SecondaryPhotoUrls = "[\"https://picsum.photos/seed/piscina-oradea-2/800/500\",\"https://picsum.photos/seed/piscina-oradea-3/800/500\"]",
                            Sports = "swimming",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "Calea Bihorului 100, Oradea",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Details = "Pistă dedicată ciclismului în Parcul Brătianu, cu o lungime de 3,5 km. Suprafață asfaltată, separată de trafic, înconjurată de vegetație. Acces liber, deschis publicului.",
                            HasLights = false,
                            Latitude = 47.055100m,
                            Longitude = 21.933100m,
                            MainPhotoUrl = "https://picsum.photos/seed/ciclism-oradea/800/500",
                            Name = "Pista de Ciclism Parcul Brătianu",
                            SecondaryPhotoUrls = "[\"https://picsum.photos/seed/ciclism-oradea-2/800/500\",\"https://picsum.photos/seed/ciclism-oradea-3/800/500\"]",
                            Sports = "cycling",
                            Status = 1,
                            Surface = "asphalt"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Calea Sântandrei 77, Oradea",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Details = "Complex cu 6 terenuri de tenis (4 zgură, 2 hard), iluminat nocturn, sală de forță și vestiare. Găzduiește turnee locale și regionale pe tot parcursul anului.",
                            HasLights = true,
                            Latitude = 47.071200m,
                            Longitude = 21.928700m,
                            MainPhotoUrl = "https://picsum.photos/seed/tenis-oradea/800/500",
                            Name = "Complexul de Tenis Lotus",
                            SecondaryPhotoUrls = "[\"https://picsum.photos/seed/tenis-oradea-2/800/500\",\"https://picsum.photos/seed/tenis-oradea-3/800/500\"]",
                            Sports = "tennis",
                            Status = 1,
                            Surface = "clay"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Calea Borșului 35, Oradea",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Details = "Sală polivalentă modernă cu o capacitate de 5.000 de locuri. Teren de baschet omologat FIBA, folosit pentru meciurile echipei CSM Oradea. Dispune de parcare, restaurant și magazine.",
                            HasLights = true,
                            Latitude = 47.062100m,
                            Longitude = 21.907300m,
                            MainPhotoUrl = "https://picsum.photos/seed/arena-oradea/800/500",
                            Name = "XT Gold Arena",
                            SecondaryPhotoUrls = "[\"https://picsum.photos/seed/arena-oradea-2/800/500\",\"https://picsum.photos/seed/arena-oradea-3/800/500\"]",
                            Sports = "basketball,handball",
                            Status = 1,
                            Surface = "hardcourt"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Str. Universității 1, Oradea",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Details = "Sală universitară cu terenuri de volei, baschet și badminton. Folosită pentru competiții studențești și antrenamente de club. Program extins în weekenduri.",
                            HasLights = true,
                            Latitude = 47.046900m,
                            Longitude = 21.933200m,
                            MainPhotoUrl = "https://picsum.photos/seed/sala-uni-oradea/800/500",
                            Name = "Sala de Sport a Universității",
                            SecondaryPhotoUrls = "[\"https://picsum.photos/seed/sala-uni-oradea-2/800/500\",\"https://picsum.photos/seed/sala-uni-oradea-3/800/500\"]",
                            Sports = "volleyball,basketball,badminton",
                            Status = 1,
                            Surface = "hardcourt"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Str. General Magheru 1, Oradea",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Details = "Pistă de atletism cu 8 culoare, suprafață tartan omologată IAAF. Include sectoare pentru sărituri în lungime, înălțime și aruncări. Deschisă publicului în afara competițiilor.",
                            HasLights = false,
                            Latitude = 47.051200m,
                            Longitude = 21.924100m,
                            MainPhotoUrl = "https://picsum.photos/seed/atletism-oradea/800/500",
                            Name = "Pista de Atletism Iuliu Bodola",
                            SecondaryPhotoUrls = "[\"https://picsum.photos/seed/atletism-oradea-2/800/500\",\"https://picsum.photos/seed/atletism-oradea-3/800/500\"]",
                            Sports = "athletics",
                            Status = 1,
                            Surface = "tartan"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Str. Menumorut 3, Oradea",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Details = "Sală cu capacitate de 2.500 locuri, dedicată handbalului și altor sporturi de sală. Teren omologat EHF, iluminat profesional și sistem de sonorizare.",
                            HasLights = true,
                            Latitude = 47.052100m,
                            Longitude = 21.920100m,
                            MainPhotoUrl = "https://picsum.photos/seed/sala-sport-oradea/800/500",
                            Name = "Sala Sporturilor Oradea",
                            SecondaryPhotoUrls = "[\"https://picsum.photos/seed/sala-sport-oradea-2/800/500\",\"https://picsum.photos/seed/sala-sport-oradea-3/800/500\"]",
                            Sports = "handball",
                            Status = 1,
                            Surface = "hardcourt"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Piața Unirii 4, Oradea",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Details = "Centru fitness modern în inima Oradei, cu echipamente cardio și de forță de ultimă generație. Clase de grup, personal traineri certificați, saună și zone de stretching.",
                            HasLights = true,
                            Latitude = 47.047800m,
                            Longitude = 21.919400m,
                            MainPhotoUrl = "https://picsum.photos/seed/fitness-oradea/800/500",
                            Name = "Centrul Fitness SportMap Park",
                            SecondaryPhotoUrls = "[\"https://picsum.photos/seed/fitness-oradea-2/800/500\",\"https://picsum.photos/seed/fitness-oradea-3/800/500\"]",
                            Sports = "fitness",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            Address = "Str. Republicii 22, Oradea",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Details = "Sala Clubului Sportiv Crișul, cu ring omologat pentru competiții naționale, saci de box, apărători și echipament complet. Antrenori cu experiență internațională.",
                            HasLights = true,
                            Latitude = 47.046500m,
                            Longitude = 21.918900m,
                            MainPhotoUrl = "https://picsum.photos/seed/box-oradea/800/500",
                            Name = "Sala de Box Crișul",
                            SecondaryPhotoUrls = "[\"https://picsum.photos/seed/box-oradea-2/800/500\",\"https://picsum.photos/seed/box-oradea-3/800/500\"]",
                            Sports = "boxing",
                            Status = 1
                        });
                });

            modelBuilder.Entity("SportMap.Core.Entities.Participation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("UserId", "ActivityId")
                        .IsUnique();

                    b.ToTable("Participations", (string)null);
                });

            modelBuilder.Entity("SportMap.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmailConfirmationToken")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("EmailConfirmationTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("FavoriteSports")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsEmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SportMap.Core.Entities.Activity", b =>
                {
                    b.HasOne("SportMap.Core.Entities.Location", "Location")
                        .WithMany("Activities")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportMap.Core.Entities.User", "Organizer")
                        .WithMany("OrganizedActivities")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("SportMap.Core.Entities.Friendship", b =>
                {
                    b.HasOne("SportMap.Core.Entities.User", "Followee")
                        .WithMany()
                        .HasForeignKey("FolloweeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportMap.Core.Entities.User", "Follower")
                        .WithMany()
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Followee");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("SportMap.Core.Entities.Location", b =>
                {
                    b.HasOne("SportMap.Core.Entities.User", "ProposedBy")
                        .WithMany()
                        .HasForeignKey("ProposedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProposedBy");
                });

            modelBuilder.Entity("SportMap.Core.Entities.Participation", b =>
                {
                    b.HasOne("SportMap.Core.Entities.Activity", "Activity")
                        .WithMany("Participations")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportMap.Core.Entities.User", "User")
                        .WithMany("Participations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportMap.Core.Entities.Activity", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("SportMap.Core.Entities.Location", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("SportMap.Core.Entities.User", b =>
                {
                    b.Navigation("OrganizedActivities");

                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
